version: 2
jobs:
  build_latest:
    docker:
      - image: circleci/node:14.17.6-browsers
    working_directory: ~/twhelp
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      # build the application image
      - run: docker build -t $DOCKER_LOGIN/twhelp-version-website:latest .
      # deploy the image
      - run: docker push $DOCKER_LOGIN/twhelp-version-website:latest
  build_version:
    docker:
      - image: circleci/node:14.17.6-browsers
    working_directory: ~/twhelp
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      # build the application image
      - run: docker build -t $DOCKER_LOGIN/twhelp-version-website:$(echo $CIRCLE_TAG | sed -r 's/^.{1}//') .
      # deploy the image
      - run: docker push $DOCKER_LOGIN/twhelp-version-website:$(echo $CIRCLE_TAG | sed -r 's/^.{1}//')
workflows:
  version: 2
  deploy_latest:
    jobs:
      - build_latest:
          context: TWHelp
          filters:
            branches:
              only:
                - master
  deploy_version:
    jobs:
      - build_version:
          context: TWHelp
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
